services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://192.168.37.18:8080
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
